name: Test Linux Image
on:
    push:
        branches:
            - main

jobs:
    BIOS:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install Softwares
                run: |
                    sudo apt update
                    sudo apt install -y python3 python3-pip python-is-python3
                    sudo apt install -y qemu-system-x86 squashfs-tools xorriso

            -   name: Install dependencies
                run: pip install -r requirements.txt

            -   name: Build Image
                run: |
                    mkdir -p fakeFolder
                    touch fakeFolder/fakeFile.txt
                    sudo python main.py image.iso -f fakeFolder -c "cmd.exe /c echo Hello World" -o linux --debug
                
            -   name: Test Image
                run: python __tests__/test.py image.iso --type bios

    UEFI:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install Softwares
                run: |
                    sudo apt update
                    sudo apt install -y python3 python3-pip python-is-python3
                    sudo apt install -y qemu-system-x86 squashfs-tools xorriso

            -   name: Install dependencies
                run: pip install -r requirements.txt

            -   name: Build Image
                run: |
                    mkdir -p fakeFolder
                    touch fakeFolder/fakeFile.txt
                    sudo python main.py image.iso -f fakeFolder -c "cmd.exe /c echo Hello World" -o linux --debug

            -   name: Test Image
                run: python __tests__/test.py image.iso --type uefi
